- hosts: test-server
  remote_user: optiedge
  
  

  tasks:
  - name: copy UI jar to remote server
    copy:
      src: /var/lib/jenkins/workspace/test1/optiedge_ui/target/OptiEdge_UI-0.0.1-SNAPSHOT.jar
      dest: /work/Optiedge/ 
  
  - name: copy API jar to remote server
    copy:
      src: /var/lib/jenkins/workspace/test1/optiedge_api/target/OptiEdge_API-0.0.1-SNAPSHOT.jar
      dest: /work/Optiedge/ 

  - name: copy Auth jar to remote server
    copy:
      src: /var/lib/jenkins/workspace/test1/optiedge_auth/target/OptiEdge_Auth-0.0.1-SNAPSHOT.jar
      dest: /work/Optiedge/
  
  - name: copy MQ jar to remote server
    copy:
      src: /var/lib/jenkins/workspace/test1/optiedge_mq/target/OptiEdge_MQ-0.0.1-SNAPSHOT.jar
      dest: /work/Optiedge 

  - name: copy Workflow jar to remote server
    copy:
      src: /var/lib/jenkins/workspace/test1/optiedge_workflow/target/OptiEdge_Workflow-0.0.1-SNAPSHOT.jar
      dest: /work/Optiedge/


  - name: copy Email jar to remote server
    copy:
      src: /var/lib/jenkins/workspace/test1/optiedge_email/target/OptiEdge_Email-0.0.1-SNAPSHOT.jar
      dest: /work/Optiedge/  

  - name: Kill service
    command: nohup java -jar /work/Optiedge/OptiEdge_UI-0.0.1-SNAPSHOT.jar    >> /work/log/OptiEdge_UI.log & 2>&1

  
 
    
