- hosts: test-server
  
  become: yes
  

  tasks:
  - name: copy UI jar to remote server
    copy:
      src: /var/lib/jenkins/workspace/test1/optiedge_ui/target/OptiEdge_UI-0.0.1-SNAPSHOT.jar
      dest: /work/ 
